server:
  port: 18080

#spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/views/


error:
  error403: /webapp/WEB-INF/views/error/403.html
  error404: error/404.html
  error500: /webapp/WEB-INF/views/error/500.html
